// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:github_user_explorer/domain/model/history_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryEntryAdapter());
  }
}
